### ISSUE TITLE
画像から正規表現を使って金額を取得できなかった際の処理を考える

### ISSUE THREAD

**Issue by ogaogs** [AyumuOgasawara/receipt-scanner-model#29]
## 概要
現在のコードは、レシートにキーワードがあることを前提に書いているが、それがなかった場合の対処法を考える。

## サンプルデータ
![IMG_9159](https://github.com/user-attachments/assets/aa339171-bd44-46f6-9c13-c5d1d9673119)

**Comment by ogaogs** [comment]
何も取得できるテキストがない場合には、以下のところでエラーが起きる。

``` sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ayumu/my-projects/receipt-scanner-model/src/receipt_scanner_model/main.py", line 53, in <module>
    print(get_receipt_detail(IMAGE))
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayumu/my-projects/receipt-scanner-model/src/receipt_scanner_model/main.py", line 30, in get_receipt_detail
    analyzed_date = analyze.scan(img_bytes)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayumu/my-projects/receipt-scanner-model/src/receipt_scanner_model/analyze.py", line 144, in scan
    total = get_total(text)
            ^^^^^^^^^^^^^^^
  File "/Users/ayumu/my-projects/receipt-scanner-model/src/receipt_scanner_model/analyze.py", line 129, in get_total
    return get_most_likely(kws_dict, totals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayumu/my-projects/receipt-scanner-model/src/receipt_scanner_model/analyze.py", line 82, in get_most_likely
    return dict_max(count_dict)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayumu/my-projects/receipt-scanner-model/src/receipt_scanner_model/analyze.py", line 94, in dict_max
    return max([max_counts_dict[i][0] for i in range(len(max_counts_dict))])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```

**Comment by ogaogs** [comment]
よってここで、以下のようにし、エラーが起きたら、0を返すようにする

``` python
    if len(max_counts_dict) == 1:
        return max_counts_dict[0][0]
    else:
        try:
            return max([max_counts_dict[i][0] for i in range(len(max_counts_dict))])
        except Exception:
            return 0
```
